name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - envisage
  - yaml
  - pyyaml
  - pyqt
  - pyzmq
  - importlib_resources
  - sqlalchemy
  - pyserial
  - bezier=2021.2.12=pypi_0
