name: Python Package using Anaconda

on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Install Qt dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev
          sudo apt-get install qtchooser
          sudo apt-get install qt5-qmake
          sudo apt-get install qtbase5-dev-tools
          sudo apt-get install libegl1
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install libxcb-icccm4
          sudo apt-get install libxcb-image0
          sudo apt-get install libxcb-keysyms1
          sudo apt-get install libxcb-randr0
          sudo apt-get install libxcb-render-util0
          sudo apt-get install libxcb-xinerama0
          sudo apt-get install libxcb-shape0
        if: matrix.toolkit != 'wx'
      - name: Install Wx dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install libsdl1.2-dev
        if: matrix.toolkit == 'wx'
      - name: Install GL dependencies for Linux
        run: sudo apt-get install libglu1-mesa-dev
      - name: Install test dependencies
        run: python -m pip install pytest wheel click coverage pyparsing celiagg
      - name: Install dependencies
        run: python -m pip install --upgrade bezier --no-binary=bezier envisage chaco importlib_resources
      - name: Tests
        run: pytest --rootdir=test

#      - uses: actions/checkout@v2
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install dependencies
#        run: |
#          # $CONDA is an environment variable pointing to the root of the miniconda directory
#          $CONDA/bin/conda env update --file environment.yml --name base python=${{ matrix.python-version }}
##      - name: Lint with flake8
##        run: |
##          $CONDA/bin/conda install flake8
##          # stop the build if there are Python syntax errors or undefined names
##          $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
##          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
##          $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#      - name: Test with pytest
#        run: |
#          conda install pytest
#          pip install -r test_requirements.txt
#          $CONDA/bin/pytest --rootdir=test
